### ISSUE TITLE
Flushing the cache doesn't work as intended

### ISSUE THREAD

**Issue by michael-e** [symphonists/cacheabledatasource#12]
While trying to debug a [performance issue](https://github.com/symphonists/cacheabledatasource/issues/11), I noticed something strange. The array that was returned by `__fetchSectionsFromContext()` looked like this:

``` php
array (
  0 => '6',
  1 => '1',
  2 => '6',
  3 => '21',
  4 => '111',
)
```

The section in question (i.e. the one the saved entry belonged to) has ID 6 — but it occured twice in the array. Apart from that, there were 3 associated sections. Next I looked at the database query which is used to find _associated_ sections:

``` php
$associatedSections = Symphony::Database()->fetch(
    sprintf('SELECT DISTINCT `child_section_id` value, `parent_section_id` value FROM `tbl_sections_association` 
        WHERE `parent_section_id` = %d OR `child_section_id` = %d',
        $this->_sectionsToFlush[0],
        $this->_sectionsToFlush[0]
    )
);
```

It returned:

```
+-------+-------+
| value | value |
+-------+-------+
|     6 |     1 |
|    50 |     6 |
|     6 |    21 |
|     6 |   111 |
+-------+-------+
```

Aha. So the extension attempts to find parent sections **and** child sections. In my case section 6 has child sections 1, 21 and 111. In addition to that, section 6 is a child section of section 50.

But the array is flattened afterwards, so it contains only the right "column". How bad.

(Please note that the saved entry's section—number 6 in my example—will be added to the array some lines later.)

**I assume that it is desirable to find parent relations and child relations alike**, because Symphony doesn't assume any "direction" for a relation (and there are fields allowing both "directions"). In this is true, the above behaviour is a bug, and it is the fault of a database query which is definitely wrong.

To fix this behaviour, one might use something like

``` php
sprintf('SELECT `child_section_id` AS value FROM `sym_sections_association`
        WHERE `parent_section_id` = %d
    UNION SELECT `parent_section_id` FROM `sym_sections_association`
        WHERE `child_section_id` = %d',
    $this->_sectionsToFlush[0],
    $this->_sectionsToFlush[0]
)
```

which would show the desired output:

```
+-------+
| VALUE |
+-------+
|    50 |
|     1 |
|    21 |
|   111 |
+-------+
```

(We should remove `General::flattenArray($associatedSections);` then.)

I would appreciate feedback on this before sending a pull request.

**Comment by nitriques** [comment]
Late to the party, but it seems like @brendo already fixed it in 99c4ed0...1c32103

I'll release ASAP.
