### ISSUE TITLE
Datasource Filters

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/cacheabledatasource#17]
When creating names for the cache files, Cacheable Datasource only takes the values of datasource filters into account (it just `implodes` the values):

```php
// get resolved values of each public property of this DS
// (sort, filters, included elements etc.)
foreach (get_class_vars(get_class($datasource)) as $key => $value) {
	if (substr($key, 0, 2) == 'ds') {
		$value = $datasource->{$key};
		$filename .= $key . (is_array($value) ? implode($value) : $value);
	}
}
```

As a result, the extension fails to create a new cache file, if two different filters have the same value. I googled a bit and using `http_build_query` seems to do the trick:

```php
// get resolved values of each public property of this DS
// (sort, filters, included elements etc.)
foreach (get_class_vars(get_class($datasource)) as $key => $value) {
	if (substr($key, 0, 2) == 'ds') {
		$value = $datasource->{$key};
		$filename .= $key . (is_array($value) ? http_build_query($value) : $value);
	}
}
```

**Comment by nitriques** [comment]
Just to make thing clearer, you are saying that only VALUES are taken into account, not the name of the variable/member ?

If so, yes, http_build_query is a good choice, but I would also sort the values by keys, just to be sure (as we did in the cache lite extension). I do not think that neither `get_class_vars` nor `http_build_query` have defined behavior regarding the order of things.

**Comment by nilshoerrmann** [comment]
The extension takes the variable names into account. But if a variable is an array it just implodes its values, trashing the keys. In the context of field filters, the extention just ignores the field id/value mapping: two pages filtering a DS on different checkboxes will generate the same cache file because only their (identical) values `yes` will be stored in the file name.

**Comment by nitriques** [comment]
Aaaaaa! Ok well then your fix makes perfect sense. I would also try to sort the filter array.

**Comment by nilshoerrmann** [comment]
I just created a pull request with my change and a few other things. Maybe you could have a look at #18 and review it, Nicolas? Thanks!

**Comment by nitriques** [comment]
LGTM! Thanks Nils!
