### ISSUE TITLE
Allow cache expiration value -1 to not expire the cache, unless entries are updated/created

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/cacheabledatasource#23]
Allow cache expiration value -1 to not expire the cache, unless entries are updated/created.

Advantages

- Less work to configure: -1  and not 99999999999 which gets transformed to 9123456546456 (easier to check/search in the code editor )
- Less cache files
- Faster (no need to create the cache files so often)

**Comment by wdebusschere** [comment]
-1 is not possible, becomes 0 after saving, alternative? 999999?

**Comment by nitriques** [comment]
-1 should be possible

**Comment by wdebusschere** [comment]
@nitriques  Could you test this? here after saving it's 0

**Comment by nitriques** [comment]
@wdebusschere change this line https://github.com/symphonists/cacheabledatasource/blob/master/extension.driver.php#L419 to -1;

Also, please add docs about that change. Thanks!

**Comment by nitriques** [comment]
i.e. -1 infinite cache, 0 disabled cache, >0 in seconds... (this is done in the js file BTW)

**Comment by nitriques** [comment]
Fixed in 48c6e0504b957b01eb2a4f7abf42d1ca91cf3df3
